#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT_DIR"

DEVICE=${DEVICE:-ufi003}
PREBUILT="prebuilt/$DEVICE"
OUTPUT=files

if [ ! -d "$PREBUILT" ]; then
    echo "ERROR: prebuilt device directory is missing: $PREBUILT" >&2
    exit 1
fi
mkdir -p "$OUTPUT"

# hyp.mbn and aboot.mbn are generated by build_hyp_aboot.sh. Never overwrite
# them with stale prebuilt files: the generated aboot contains boot-fastboot.
for generated in hyp.mbn aboot.mbn lk2nd.img; do
    if [ ! -s "$OUTPUT/$generated" ]; then
        echo "ERROR: generated firmware is missing: $OUTPUT/$generated" >&2
        exit 1
    fi
done
rm -f "$OUTPUT/aboot.bin"

for firmware in rpm.mbn sbl1.mbn tz.mbn gpt_both0.bin; do
    source_file="$PREBUILT/$firmware"
    if [ ! -s "$source_file" ]; then
        echo "ERROR: required prebuilt firmware is missing: $source_file" >&2
        exit 1
    fi
    cp "$source_file" "$OUTPUT/$firmware"
done

# Add a raw 1 MiB misc partition in the existing fsg/aboot gap. The helper
# preserves all existing LBAs and GUIDs, updates both packed GPT tables, and
# recalculates the table/header CRCs before replacing the copied image.
python3 scripts/gpt.py add-misc "$OUTPUT/gpt_both0.bin"
python3 scripts/gpt.py validate "$OUTPUT/gpt_both0.bin"
